"""
Pentagon numbers
Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70
− 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of
D?
"""
import time

__date__ = '14-3-25'
__author__ = 'SUN'

def is_pentagonal(n):
    root = (1 + (1 + 24 * n) ** 0.5) / 6
    return root == int(root)

if __name__ == '__main__':
    start = time.clock()
    pen = [1, 5]
    i = 3
    diff = 0
    next_pen = i * (3 * i - 1) // 2
    isInPen = False
    while not isInPen:
        for value in pen:
            if (next_pen - value) in pen and is_pentagonal(next_pen + value):
                isInPen = True
                diff = next_pen - value
                break
        pen.append(next_pen)
        i += 1
        next_pen = i * (3 * i - 1) // 2
    print(diff)
    print('Runtime is ', time.clock() - start)